/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Password;
import javax.swing.JOptionPane;


/**
 *
 * @author walbonis1
 */


public class Principal extends javax.swing.JFrame {
int longitud;
 String contraseniaa;
    
    
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        txtLongitud1.setText("8");
        txtLongitud1.requestFocusInWindow();
        txtLongitud1.selectAll();
        cmdCambiar.setEnabled(false);
            cmdSeguridad.setEnabled(false);
            cmdMostrar.setEnabled(false);
            cmdSalir.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtContrase = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        cmdSalir = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdSeguridad = new javax.swing.JButton();
        cmdCambiar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdListo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("contraseña ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("longitud ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtLongitud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitud1ActionPerformed(evt);
            }
        });
        txtLongitud1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitud1KeyTyped(evt);
            }
        });
        jPanel1.add(txtLongitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 70, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("ingrese su contraseña");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 20));

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 110));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Su Contraseña");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtContrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseActionPerformed(evt);
            }
        });
        txtContrase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseKeyTyped(evt);
            }
        });
        jPanel2.add(txtContrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, 240));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdSalir.setBackground(new java.awt.Color(255, 0, 51));
        cmdSalir.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cmdSalir.setForeground(new java.awt.Color(0, 255, 255));
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, -1));

        cmdBorrar.setBackground(new java.awt.Color(255, 153, 153));
        cmdBorrar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cmdBorrar.setForeground(new java.awt.Color(0, 255, 255));
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, -1));

        cmdSeguridad.setBackground(new java.awt.Color(102, 102, 102));
        cmdSeguridad.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cmdSeguridad.setForeground(new java.awt.Color(0, 255, 255));
        cmdSeguridad.setText("Ver Seguridad");
        cmdSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeguridadActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, -1));

        cmdCambiar.setBackground(new java.awt.Color(102, 102, 102));
        cmdCambiar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cmdCambiar.setForeground(new java.awt.Color(0, 255, 255));
        cmdCambiar.setText("Cambiar Contraseña");
        cmdCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        cmdMostrar.setBackground(new java.awt.Color(102, 102, 102));
        cmdMostrar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cmdMostrar.setForeground(new java.awt.Color(0, 255, 255));
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, -1));

        cmdListo.setBackground(new java.awt.Color(102, 102, 102));
        cmdListo.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cmdListo.setForeground(new java.awt.Color(0, 255, 255));
        cmdListo.setText("Listo");
        cmdListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdListoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 160, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(694, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
     System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListoActionPerformed
        Password p, p1;
        Password password2;
            int longitud = 8;
            String pass;
            pass = txtContrase.getText();
            password2 = new Password(longitud, pass);
            longitud = Integer.parseInt(txtLongitud1.getText());
            password2.setLongitud(longitud);
            
           if(txtLongitud1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la Longitud", "error", JOptionPane.ERROR_MESSAGE);
            txtLongitud1.requestFocusInWindow();
    }else  if (txtContrase.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Contraseña", "error", JOptionPane.ERROR_MESSAGE);
            txtContrase.requestFocusInWindow();
        }else if (longitud != pass.length()) {
                JOptionPane.showMessageDialog(this, "La contraseña no coincide con la longitud", "ERROR", JOptionPane.ERROR_MESSAGE); 
        }else {
            contraseniaa = txtContrase.getText();
            longitud = contraseniaa.length();
            
            p = new Password(longitud, contraseniaa);
            JOptionPane.showMessageDialog(this, "Contraseña guardada");
            
            cmdCambiar.setEnabled(true);
            cmdSeguridad.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdBorrar.setEnabled(true);
            cmdListo.setEnabled(false);
            cmdSalir.setEnabled(false);
            txtContrase.setEditable(false);
             cmdSalir.setEnabled(false);
            
            
        }
    }//GEN-LAST:event_cmdListoActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
       Password pa, c;

        contraseniaa = txtContrase.getText();
        longitud = contraseniaa.length();
        pa = new Password(longitud, contraseniaa);
        c = pa.ver();
        txtResultado.setText("Su contraseña es: " + c.getContrasena()+ "\n" + " longitud de su contraseña es: " + c.getLongitud());
         cmdSalir.setEnabled(false);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarActionPerformed
     txtLongitud1.setEditable(false);
       cmdListo.setEnabled(true);
       txtContrase.setEditable(true);
        txtContrase.selectAll();
        txtContrase.requestFocusInWindow();
        cmdMostrar.setEnabled(false);
        cmdCambiar.setEnabled(false);
        cmdSeguridad.setEnabled(false); 
         cmdSalir.setEnabled(false);
    }//GEN-LAST:event_cmdCambiarActionPerformed

    private void cmdSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeguridadActionPerformed
      String contra;
        Password cla;
        contraseniaa = txtContrase.getText();
        longitud= contraseniaa.length();
        cla = new Password(longitud, contraseniaa);
        contra = cla.fuerte();
        txtResultado.setText(contra);
    }//GEN-LAST:event_cmdSeguridadActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       txtLongitud1.setText("8");
        txtContrase.setText("");
        txtResultado.setText("");
        cmdListo.setEnabled(true);
        cmdCambiar.setEnabled(false);
        cmdSeguridad.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdBorrar.setEnabled(false);
        txtContrase.setEditable(true);
         cmdSalir.setEnabled(true);
        txtLongitud1.requestFocusInWindow();
        txtLongitud1.selectAll();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtLongitud1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitud1KeyTyped
       char c=evt.getKeyChar();
             
         
          if(!Character.isDigit(evt.getKeyChar())){ 
              getToolkit().beep(); 
               
              evt.consume(); 
          }
    }//GEN-LAST:event_txtLongitud1KeyTyped

    private void txtContraseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseKeyTyped
  
    }//GEN-LAST:event_txtContraseKeyTyped

    private void txtContraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseActionPerformed

    private void txtLongitud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitud1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitud1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCambiar;
    private javax.swing.JButton cmdListo;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JButton cmdSeguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtContrase;
    private javax.swing.JTextField txtLongitud1;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
